image: archlinux/base:latest

stages:
  - babl
  - gegl
  - gimp

variables:
  INSTALL_DIR: "_install"
  INSTALL_PREFIX: "${CI_PROJECT_DIR}/${INSTALL_DIR}"
  PACMAN_CACHE:   "${CI_PROJECT_DIR}/_pacman_cache"

cache:
  paths:
  - _pacman_cache

# set up the build environment for all subsequent steps
before_script:
  - pacman -Syu --noconfirm --needed --cachedir "${PACMAN_CACHE}"
    alsa-lib
    appstream-glib
    at-spi2-atk
    at-spi2-core
    base-devel
    dbus-glib
    desktop-file-utils
    ffmpeg
    ghostscript
    git
    glib-networking
    gobject-introspection
    graphviz
    gtk-doc
    gtk2
    hicolor-icon-theme
    intltool
    iso-codes
    jasper
    json-glib
    lcms2
    libexif
    libgexiv2
    libgudev
    libheif
    libmng
    libmypaint
    libraw
    librsvg
    libspiro
    libtiff
    libwebp
    libwmf
    libxmu
    libxpm
    luajit
    meson
    mypaint-brushes1
    openexr
    openexr
    poppler-data
    poppler-glib
    pygtk
    python
    sdl2
    suitesparse
    xorg-server-xvfb
    xorgproto

.babl-base:
  stage: babl
  artifacts:
    paths:
    - "${INSTALL_DIR}"
  variables:
    GIT_DEPTH: "5"
  before_script:
    - export PKG_CONFIG_PATH="${INSTALL_PREFIX}/lib/pkgconfig"
    - export LD_LIBRARY_PATH="${INSTALL_PREFIX}/lib:${LD_LIBRARY_PATH}"
    - export XDG_DATA_DIRS="${INSTALL_PREFIX}/share:/usr/local/share:/usr/share"
    - git clone --depth="${GIT_DEPTH}" https://gitlab.gnome.org/GNOME/babl.git _babl

babl-git:
  extends: .babl-base
  script:
    - cd _babl
    - meson -Dprefix="${INSTALL_PREFIX}" _build
    - ninja -C _build
    - ninja -C _build install

.gegl-base:
  stage: gegl
  artifacts:
    paths:
    - "${INSTALL_DIR}"
  variables:
    GIT_DEPTH: "5"
  before_script:
    - export PKG_CONFIG_PATH="${INSTALL_PREFIX}/lib/pkgconfig"
    - export LD_LIBRARY_PATH="${INSTALL_PREFIX}/lib:${LD_LIBRARY_PATH}"
    - export XDG_DATA_DIRS="${INSTALL_PREFIX}/share:/usr/local/share:/usr/share"
    - git clone --depth=${GIT_DEPTH} https://gitlab.gnome.org/GNOME/gegl.git _gegl

gegl-git:
  extends: .gegl-base
  script:
    - cd _gegl
    - meson --prefix="${INSTALL_PREFIX}" _build
    - ninja -C _build
    - ninja -C _build install

.gimp-base:
  stage: gimp
  artifacts:
    paths:
    - "${INSTALL_DIR}"
  variables:
    GIT_DEPTH: "5"
  before_script:
    - export PKG_CONFIG_PATH="${INSTALL_PREFIX}/lib/pkgconfig:${INSTALL_PREFIX}/share/pkgconfig"
    - export LD_LIBRARY_PATH="${INSTALL_PREFIX}/lib:${LD_LIBRARY_PATH}"
    - export XDG_DATA_DIRS="${INSTALL_PREFIX}/share:/usr/local/share:/usr/share"

.gimp-autotools:
  extends: .gimp-base
  script:
    - mkdir _build
    - cd _build
    - ../autogen.sh
        --prefix="${INSTALL_PREFIX}"
        --enable-debug
    - make -j "$(nproc)"
    # - make check
  # artifacts:
  #   name: "app-tests-logs-${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
  #   when: on_failure
  #   expire_in: 1 week
  #   paths:
  #     - _build/app/tests/

build-git-autotools:
  extends: .gimp-autotools
  dependencies:
    - babl-git
    - gegl-git
